#!/bin/sh
### BEGIN INIT INFO
# Provides:          prometheus-dns-test-exporter
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the prometheus dns test exporter
# Description:       starts prometheus-dns-test-exporter using start-stop-daemon
### END INIT INFO

DESC="Prometheus DNS Test Exporter for machine metrics"
NAME=prometheus-dns-test-exporter
DAEMON=/usr/bin/prometheus-dns-test-exporter

DAEMONUSER=root
PIDFILE=/var/run/$NAME.pid
CONFIGFILE=/etc/prometheus/dns-test.yml

STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"

test -x $DAEMON || exit 0

# allow overwriting variables
#   Debian based
[ -e "/etc/default/prometheus-dns-test-exporter" ] && . /etc/default/prometheus-dns-test-exporter

if [ -z "$ARGS" ]; then
    # daemon options
    ARGS="--config.file $CONFIGFILE"
fi


start() {
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
        --background --chuid $DAEMONUSER --oknodo --exec $DAEMON -- $ARGS
}

stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry=$STOP_SCHEDULE \
        --exec $DAEMON --oknodo
    rm -f $PIDFILE
}

reload() {
    start-stop-daemon --stop --quiet --signal USR1 --pidfile $PIDFILE \
        --exec $DAEMON
}

status() {
    if [ -f $PIDFILE ]; then
        if kill -0 $(cat "$PIDFILE"); then
            echo "$NAME is running"
        else
            echo "$NAME process is dead, but pidfile exists"
            exit 3
        fi
    else
        echo "$NAME is not running"
        exit 3
    fi
}

case "$1" in
    start)
        echo "Starting $NAME"
        start
    ;;
    stop)
        echo "Stopping $NAME"
        stop
    ;;
    restart)
        echo "Restarting $NAME"
        stop
        start
    ;;
    reload)
        echo "Reloading $NAME configuration"
        reload
    ;;
    status)
        status
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 2
    ;;
esac

exit 0
